# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFuAnNN2vNSlY6ti2pzguIuSRxT24INl
"""

'''sortings :
 bubble
 counting sort '''

'''
Algo:
1.start from the beginning of the array/list2.
2.compare each pair to adjacent number
3.if latest element is greater than adjscent
4.repeat the process till n-1
5.after each pass/cycle,largest unsorted element would be in correct pos
6.repeat pass till all the elements are sorted
pseudo:
for  i ->0 to n-1:
for j ->0 to n-i-2:
if a[j]>a[j+1]:
swap(a[j],a[j+1])
'''


def bubble_sort(arr):
  n=len(arr)
  for i in range(n):
    for j in range(0,n-i-1):
      if arr[j]>arr[j+1]:
        arr[j],arr[j+1]=arr[j+1],arr[j]
size=int(input("Enter  the number of elements:"))
arr=[]
print("Enter the elements:")
for _ in range(size):
    arr.append((input(_)))
print("Original list:",arr)
bubble_sort(arr)
print("BubbleSorted:",arr)



