# -*- coding: utf-8 -*-
"""cpt10/07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhkbFPuh0ODIuzKGxc7YRVirw7dJ-8Ii
"""

def csortString(s):
  count=[0]*26
  for char in s:
    count[ord(char)-ord('a')]+=1
  sorted_str=''
  for i in range(26):
    sorted_str+=chr(i+ord('a')) *count[i]
  return sorted_str
name=input("Enter a single word")
sorted_name= csortString(name)
print("Original string:", name)
print("Sorted string :", sorted_name)

